apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
data:
  jenkins.yaml: |
    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
      globalJobDslSecurityConfiguration:
        useScriptSecurity: false
      scriptApproval:
        approvedSignatures:
        - "method groovy.json.JsonSlurper parse java.io.Reader"
    unclassified:
      slackNotifier:
        teamDomain: "your-slack-domain"
        tokenCredentialId: "slack-token"
      globalLibraries:
        libraries:
        - defaultVersion: "master"
          name: "devops-pipeline"
          retriever:
            modernSCM:
              scm:
                git:
                  credentialsId: "your-github-ssh-key"
                  remote: "your-devops-share-library-github-url"
                  traits:
                  - "branchDiscoveryTrait"
      gitHubPluginConfig:
        configs:
          - name: "GitHub"
            apiUrl: "https://api.github.com/v3/"
            credentialsId: "github-token"
            manageHooks: true
      ghprbTrigger:
        githubAuth:
          - credentialsId: "github-token"
            description: "IBM GitHub"
            serverAPIUrl: "https://api.github.com/v3/"
    jenkins:
      clouds:
      - kubernetes:
          jenkinsTunnel: "jenkins-operator-slave-jenkins.jenkins.svc.cluster.local:50000"
          jenkinsUrl: "http://jenkins-operator-http-jenkins.jenkins.svc.cluster.local:8080"
          name: "kubernetes"
          namespace: "jenkins"
          retentionTimeout: 15
          serverUrl: "https://kubernetes.default.svc.cluster.local:443"
      systemMessage: "<Cloud Native DevSecOps>"
#      securityRealm:
#        # your ldap configurationn
#        ldap:
#          configurations:
#            - server: ""
#              rootDN: ""
#              userSearchBase: ""
#              userSearch: ""
#              groupSearchBase: ""
#              groupMembershipStrategy:
#                fromGroupSearch:
#                   filter: ""
#              managerDN: ""
#              managerPasswordSecret: ""
#              displayNameAttributeName: ""
#              mailAddressAttributeName: ""
#              ignoreIfUnavailable: ""
#              inhibitInferRootDN: ""
#      authorizationStrategy:
#        globalMatrix:
#          permissions:
#            - "Overall/Read:anonymous"
#            - "Overall/Administer:authenticated"
#      authorizationStrategy:
#        projectMatrix:
#          permissions:
#          - "Agent/Build:jenkins-operator"
#          - "Agent/Build:authenticated"
#          - "Agent/Build:majinghe@cn.ibm.com"
#          - "Agent/Configure:jenkins-operator"
#          - "Agent/Configure:authenticated"
#          - "Agent/Configure:majinghe@cn.ibm.com"
#          - "Agent/Connect:jenkins-operator"
#          - "Agent/Connect:authenticated"
#          - "Agent/Connect:majinghe@cn.ibm.com"
#          - "Agent/Create:jenkins-operator"
#          - "Agent/Create:authenticated"
#          - "Agent/Create:majinghe@cn.ibm.com"
#          - "Agent/Delete:jenkins-operator"
#          - "Agent/Delete:authenticated"
#          - "Agent/Delete:majinghe@cn.ibm.com"
#          - "Agent/Disconnect:jenkins-operator"
#          - "Agent/Disconnect:authenticated"
#          - "Agent/Disconnect:majinghe@cn.ibm.com"
#          - "Credentials/Create:jenkins-operator"
#          - "Credentials/Create:authenticated"
#          - "Credentials/Create:majinghe@cn.ibm.com"
#          - "Credentials/Delete:jenkins-operator"
#          - "Credentials/Delete:authenticated"
#          - "Credentials/Delete:majinghe@cn.ibm.com"
#          - "Credentials/ManageDomains:jenkins-operator"
#          - "Credentials/ManageDomains:authenticated"
#          - "Credentials/ManageDomains:majinghe@cn.ibm.com"
#          - "Credentials/Update:jenkins-operator"
#          - "Credentials/Update:authenticated"
#          - "Credentials/Update:majinghe@cn.ibm.com"
#          - "Credentials/View:jenkins-operator"
#          - "Credentials/View:authenticated"
#          - "Credentials/View:majinghe@cn.ibm.com"
#          - "Job/Build:jenkins-operator"
#          - "Job/Build:authenticated"
#          - "Job/Build:majinghe@cn.ibm.com"
#          - "Job/Cancel:jenkins-operator"
#          - "Job/Cancel:authenticated"
#          - "Job/Cancel:majinghe@cn.ibm.com"
#          - "Job/Configure:jenkins-operator"
#          - "Job/Configure:authenticated"
#          - "Job/Configure:majinghe@cn.ibm.com"
#          - "Job/Create:jenkins-operator"
#          - "Job/Create:authenticated"
#          - "Job/Create:majinghe@cn.ibm.com"
#          - "Job/Delete:jenkins-operator"
#          - "Job/Delete:authenticated"
#          - "Job/Delete:majinghe@cn.ibm.com"
#          - "Job/Discover:jenkins-operator"
#          - "Job/Discover:authenticated"
#          - "Job/Discover:majinghe@cn.ibm.com"
#          - "Job/Move:jenkins-operator"
#          - "Job/Move:authenticated"
#          - "Job/Move:majinghe@cn.ibm.com"
#          - "Job/Read:jenkins-operator"
#          - "Job/Read:authenticated"
#          - "Job/Read:majinghe@cn.ibm.com"
#          - "Job/Workspace:jenkins-operator"
#          - "Job/Workspace:authenticated"
#          - "Job/Workspace:majinghe@cn.ibm.com"
#          - "Lockable Resources/Reserve:jenkins-operator"
#          - "Lockable Resources/Reserve:majinghe@cn.ibm.com"
#          - "Lockable Resources/Unlock:jenkins-operator"
#          - "Lockable Resources/Unlock:majinghe@cn.ibm.com"
#          - "Lockable Resources/View:jenkins-operator"
#          - "Lockable Resources/View:majinghe@cn.ibm.com"
#          - "Metrics/HealthCheck:jenkins-operator"
#          - "Metrics/HealthCheck:majinghe@cn.ibm.com"
#          - "Metrics/ThreadDump:jenkins-operator"
#          - "Metrics/ThreadDump:majinghe@cn.ibm.com"
#          - "Metrics/View:jenkins-operator"
#          - "Metrics/View:majinghe@cn.ibm.com"
#          - "Overall/Administer:jenkins-operator"
#          - "Overall/Administer:authenticated"
#          - "Overall/Administer:majinghe@cn.ibm.com"
#          - "Overall/Read:jenkins-operator"
#          - "Overall/Read:anonymous"
#          - "Overall/Read:authenticated"
#          - "Overall/Read:majinghe@cn.ibm.com"
#          - "Run/Delete:jenkins-operator"
#          - "Run/Delete:authenticated"
#          - "Run/Delete:majinghe@cn.ibm.com"
#          - "Run/Replay:jenkins-operator"
#          - "Run/Replay:authenticated"
#          - "Run/Replay:majinghe@cn.ibm.com"
#          - "Run/Update:jenkins-operator"
#          - "Run/Update:authenticated"
#          - "Run/Update:majinghe@cn.ibm.com"
#          - "SCM/Tag:jenkins-operator"
#          - "SCM/Tag:majinghe@cn.ibm.com"
#          - "View/Configure:jenkins-operator"
#          - "View/Configure:authenticated"
#          - "View/Configure:majinghe@cn.ibm.com"
#          - "View/Create:jenkins-operator"
#          - "View/Create:authenticated"
#          - "View/Create:majinghe@cn.ibm.com"
#          - "View/Delete:jenkins-operator"
#          - "View/Delete:authenticated"
#          - "View/Delete:majinghe@cn.ibm.com"
#          - "View/Read:jenkins-operator"
#          - "View/Read:authenticated"
#          - "View/Read:majinghe@cn.ibm.com"
