kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-master
  labels:
    billingType: "hourly"
    region: us-south
    zone: dal13
  annotations:
    volume.beta.kubernetes.io/storage-class: ibmc-file-gold
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-file-gold
