apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: jenkins
resources:
- jenkins_operator.yaml
- config.yaml
- jenkins.yaml
- jenkins-rbac.yaml
- jenkins-pvc.yaml

namespace: jenkins

generators:
 - ./kops-secret.yaml


generatorOptions:
  labels:
    deploy.type: kustomize
  disableNameSuffixHash: true
